zones:
  inskip:
    name: inskip.me
    records:
      - kind: caa
        flags: 0
        tag: iodef
        value: mailto:acme@inskip.me
      - kind: cname
        value: inskip-root.pages.dev
      - kind: caa
        flags: 0
        tag: issue
        value: letsencrypt.org
      - kind: caa
        flags: 0
        tag: issuewild
        value: ;
      - kind: txt
        value: v=spf1 include:_spf.google.com -all
      - kind: mx
        priority: 1
        value: aspmx.l.google.com
      - kind: txt
        name: google._domainkey
        value: v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkxag/EmXQ89XQmLrBDPpPtZ7EtEJT0hgvWf/+AFiOfBOm902tq9NbTTvRJ2dLeBLPaV+hNvq2Alc7UfkKUDlLTWQjeuiC6aOnRKQQg3LZ2W25U3AlIj0jd2IPiUhg9JGV4c66XiqQ5ylTBniShfUUyeAXxbPhYFBCkBg62LZcO/tFpFsdKWtZzLjgac5vTJID+M4F8duHpkA/ZCNNUEmtt7RNQB/LLI1Gr5yR4GdQl9z7NmwtOTo9pghbZuvljr8phYjdDrwZeFTMKQnvR1l2Eh/dZ8I0C4nP5Bk4QEfmLq666P1HzOxwT6iCU6Tc+P/pkWbrx0HJh39E1aKGyLJMQIDAQAB
      - kind: mx
        priority: 5
        value: alt1.aspmx.l.google.com
      - kind: mx
        priority: 5
        value: alt2.aspmx.l.google.com
      - kind: mx
        priority: 10
        value: alt3.aspmx.l.google.com
      - kind: mx
        priority: 10
        value: alt4.aspmx.l.google.com
      - kind: mx
        priority: 15
        value: 6uyykkzhqi4zgogxiicbuamoqrxajwo5werga4byh77b2iyx3wma.mx-verification.google.com
  dork:
    name: dork.dev
    records:
      - kind: txt
        name: google._domainkey
        value: v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAziwoHJbM1rmeUiIXOgg0cujTL5BFW9PQOksUhKza1XpDP2rpzTlQr21NFYMJMc08xiE3AbvScMTX0jX3gc7+XoIYLD1VigRRvkyTubVfRmatqj+Pk41Fle1jWXHv5vNIYjjcsUTrpnrXYKoYrz34TtsmYHnu0G9MgmmcQGmbRU+WY+1R/ukhavlgXasfEW6r4tjLgVxQnser1Zjr80AUcu23od/+o+m6C9rDGMMnv6NIc2DOT7Ei6o60458f2Iwcpg38te22dy46A8AeGynbpB9+jF33Se0m22eKk5qZN5mfju/wxWMsl7ifCY/eqLZXRxJaEd5bMI8px5KvZp1TWwIDAQAB
  gensokyo:
    name: gensokyo.zone
  kittywitch:
    name: kittywit.ch
    records:
      - kind: a
        name: marisa
        value: 104.244.72.5
      - kind: aaaa
        name: marisa
        value: 2605:6400:30:eed1:6cf7:bbfc:b4e:15c0
      - kind: a
        name: daiyousei
        value: 132.145.26.5
      - kind: aaaa
        name: daiyousei
        value: 2603:c020:c004:6f00::6
      - kind: cname
        name: irc
        value: daiyousei.kittywit.ch
      - kind: cname
        name: auth
        value: daiyousei.kittywit.ch
      - kind: cname
        name: vault
        value: daiyousei.kittywit.ch
      - kind: cname
        name: files
        value: daiyousei.kittywit.ch
      - kind: cname
        name: znc
        value: daiyousei.kittywit.ch
      - kind: cname
        value: daiyousei.kittywit.ch